"""Refactor

Revision ID: 4eb7655e1ad0
Revises: 4c9a9b396322
Create Date: 2025-08-20 03:11:05.275070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb7655e1ad0'
down_revision: Union[str, None] = '4c9a9b396322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_categories', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_user_categories_category_id', 'user_categories', ['category_id'], unique=False)
    op.create_index('ix_user_categories_user_id', 'user_categories', ['user_id'], unique=False)
    op.drop_constraint(op.f('user_categories_user_id_fkey'), 'user_categories', type_='foreignkey')
    op.drop_constraint(op.f('user_categories_category_id_fkey'), 'user_categories', type_='foreignkey')
    op.create_foreign_key(None, 'user_categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_categories', type_='foreignkey')
    op.drop_constraint(None, 'user_categories', type_='foreignkey')
    op.create_foreign_key(op.f('user_categories_category_id_fkey'), 'user_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('user_categories_user_id_fkey'), 'user_categories', 'users', ['user_id'], ['id'])
    op.drop_index('ix_user_categories_user_id', table_name='user_categories')
    op.drop_index('ix_user_categories_category_id', table_name='user_categories')
    op.alter_column('user_categories', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_categories', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
