"""add user categories

Revision ID: 28e47ade5c5f
Revises: 32004f9682f1
Create Date: 2025-02-05 21:41:45.659563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e47ade5c5f'
down_revision: Union[str, None] = '32004f9682f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True)
    )
    op.add_column('categories', sa.Column('slug', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.create_foreign_key(None, 'user_apps', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'user_apps', 'apps', ['app_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_apps', type_='foreignkey')
    op.drop_constraint(None, 'user_apps', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
