"""add user apps

Revision ID: 32004f9682f1
Revises: fd4cab790bd4
Create Date: 2025-02-04 18:22:20.365495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32004f9682f1'
down_revision: Union[str, None] = 'fd4cab790bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_apps',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('app_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_apps')
    # ### end Alembic commands ###
