"""change upvote to subscribers

Revision ID: 4c9a9b396322
Revises: d7545cc7ec9b
Create Date: 2025-03-29 01:30:31.020476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9a9b396322'
down_revision: Union[str, None] = 'd7545cc7ec9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('subscribers', sa.Integer(), nullable=True))
    op.drop_column('apps', 'upvotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('apps', 'subscribers')
    # ### end Alembic commands ###
