"""add subscription properties

Revision ID: 8f1b59f61856
Revises: 98e6a49d8495
Create Date: 2025-02-24 17:35:28.545165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1b59f61856'
down_revision: Union[str, None] = '98e6a49d8495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

account_type = sa.Enum('STARTER', 'PRO', 'ENTERPRISE', name='accounttype')
def upgrade() -> None:
    account_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', account_type, nullable=True))
    op.add_column('users', sa.Column('last_subscription_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('next_subscription_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('is_preference_configured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_preference_configured')
    op.drop_column('users', 'is_verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'next_subscription_date')
    op.drop_column('users', 'last_subscription_date')
    op.drop_column('users', 'account_type')
    account_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
