"""add trending to app

Revision ID: 98e6a49d8495
Revises: 28e47ade5c5f
Create Date: 2025-02-06 22:01:04.670107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e6a49d8495'
down_revision: Union[str, None] = '28e47ade5c5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('trending', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'user_categories', 'categories', ['category_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'user_categories', 'users', ['user_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_categories', type_='foreignkey')
    op.drop_constraint(None, 'user_categories', type_='foreignkey')
    op.drop_column('apps', 'trending')
    # ### end Alembic commands ###
