"""Update Models

Revision ID: c765c1bef916
Revises: ce741ddef265
Create Date: 2025-03-09 22:53:24.258597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c765c1bef916'
down_revision: Union[str, None] = 'ce741ddef265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=200), nullable=True))
    op.add_column('categories', sa.Column('app_count', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'views')
    op.drop_column('categories', 'app_count')
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
