"""Add Created_at property to all intermediary table

Revision ID: d7545cc7ec9b
Revises: f011dd700a2f
Create Date: 2025-03-19 00:49:36.224120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7545cc7ec9b'
down_revision: Union[str, None] = 'f011dd700a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_platforms', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('app_tags', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_apps', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_categories', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_categories', 'created_at')
    op.drop_column('user_apps', 'created_at')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('app_tags', 'created_at')
    op.drop_column('app_platforms', 'created_at')
    # ### end Alembic commands ###
