"""Change views to subscribers

Revision ID: f011dd700a2f
Revises: c765c1bef916
Create Date: 2025-03-09 23:14:14.476663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f011dd700a2f'
down_revision: Union[str, None] = 'c765c1bef916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('subscribers', sa.Integer(), nullable=True))
    op.drop_column('categories', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'subscribers')
    # ### end Alembic commands ###
