"""Convert banner and icon to base64

Revision ID: fd4cab790bd4
Revises: a86923f3d621
Create Date: 2025-01-18 01:58:06.928045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4cab790bd4'
down_revision: Union[str, None] = 'a86923f3d621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'app_platforms', 'platforms', ['platform_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'app_platforms', 'apps', ['app_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'app_tags', 'tags', ['tag_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'app_tags', 'apps', ['app_id'], ['id'], use_alter=True)
    op.alter_column('apps', 'icon',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('apps', 'banner',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'apps', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'apps', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'apps', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'apps', 'categories', ['category_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'categories', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'categories', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'categories', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'permissions', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'permissions', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'permissions', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'platforms', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'platforms', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'platforms', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reviews', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reviews', 'apps', ['app_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reviews', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reviews', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'roles', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'roles', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'roles', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'tags', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'tags', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'tags', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users', 'users', ['deleted_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'users', 'users', ['last_updated_by_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'platforms', type_='foreignkey')
    op.drop_constraint(None, 'platforms', type_='foreignkey')
    op.drop_constraint(None, 'platforms', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.drop_constraint(None, 'apps', type_='foreignkey')
    op.alter_column('apps', 'banner',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.alter_column('apps', 'icon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    op.drop_constraint(None, 'app_tags', type_='foreignkey')
    op.drop_constraint(None, 'app_tags', type_='foreignkey')
    op.drop_constraint(None, 'app_platforms', type_='foreignkey')
    op.drop_constraint(None, 'app_platforms', type_='foreignkey')
    # ### end Alembic commands ###
